version: 2

project_name: kubectl-regex

before:
  hooks:
    - go mod tidy

builds:
  - id: kubectl-regex
    main: ./cmd/kubectl-regex.go
    binary: kubectl-regex
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w

archives:
  - id: default
    builds: [kubectl-regex]
    format_overrides:
      - goos: windows
        format: zip
    name_template: "kubectl-regex_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE

checksum:
  name_template: "checksums.txt"

release:
  prerelease: false
